[package]
name = "werwolf"
version = "0.1.0"
authors = ["Bodokat <bod.kato@gmail.com>"]
edition = "2018"


[dependencies]
tokio = {version = "1.0", features = ["rt-multi-thread"]}
dotenv = "0.15"
rand = "0.8"
itertools = "0.10.0"
futures = "0.3"
enum_dispatch = "0.3"
async-trait = "0.1"

[dependencies.serenity]
version = "0.10"
features = ["collector"]